name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [10, 12, 13]

    env:
      NODE_ENV: test

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install yarn
        run: |
          curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
      - name: yarn build
        run: |
          yarn
      - name: yarn lint
        run: |
          yarn lint
